""" Write a function that returns the smallest non-negative number which can be generated by using all the digits with odd values of a given number. """

def solution(num):
    ans = str(num)
    ans = list(ans)
    ans = sorted(ans)
    ans = "".join(ans)
    return int(ans)

assert solution(321) == 123